export const intro = [
  {
    id: 1,
    name: "Web development",
    type: "individual project",
    time: "Nov 2022 - Dec 2022",
    summary: "A simple shopping website",
    achievements: [
      "This project is done with the help of tutorials on Udemy. The Instructor is John Smilga.",
      "Implemented a web development project using JavaScript and React.",
      "Deployed the project on Netlify to make it easily accessible to users.",
      "Created a range of components including navbar, sidebar, routers, filters, sort functionality, cart, local storage, login functionality with APIs of Auth0, checkout functionality with APIs of Stripe.",
      "Used the Auth0 and Stripe APIs to ensure secure login and checkout processes.",
    ],
    link: "https://github.com/Shaddock-L/react-prac-comfy",
  },
  {
    id: 2,
    name: "COMP9900",
    type: "group project",
    time: "Sep 2022 - Nov 2022",
    summary: "Wait management system.",
    achievements: [
      "Created a wait management system that could run on a local server with four different URLs: customer page, waiter page, kitchen page, and manager page.",
      "As the backend developer, responsible for compiling the system using Python, Flask, and MySQL.",
      "Utilized Flask-SQLAlchemy to operate on the database, allowing users to add, delete, search, and modify the database directly on the web page through APIs.",
      "Demonstrated expertise in backend development and ability to create a functional and user-friendly system with efficient database interaction.",
    ],
    link: "https://github.com/Shaddock-L/cs9900",
  },
  {
    id: 3,
    name: "COMP9517",
    time: "Jun 2022 - Jul 2022",
    type: "group project",
    summary:
      "Detect and track pedestrians from the videos with different angles, widths, and heights.",
    achievements: [
      "As the group leader of this project, I was responsible for project planning, coding, and division of labor among team members.",
      "We used the inter-frame difference method and YOLOv5 to detect pedestrians in a video. After comparing the results, we decided to use YOLOv5 for its superior performance. To track pedestrians, we utilized DeepSORT.",
      "We drew bounding boxes and corresponding trajectories for each pedestrian and reported the total count of pedestrians present in the current video frame. Our project also allowed for the analysis of pedestrian behavior over time, including walking alone or in a group.",
    ],
    link: "https://github.com/Shaddock-L/COMP9517",
  },
  {
    id: 4,
    name: "COMP9417",
    type: "group project",
    time: "Mar 2022 - Apr 2022",
    summary: "Classify different types of cancer with CNN",
    achievements: [
      "In this project, I led a team as the group leader and was responsible for project planning, division of labor, and coding the convolutional neural network (CNN) part.",
      "Our goal was to classify 3 different types of cancers. We analyzed the weights of RGB channels on different cancers. Initially, we attempted to use Gaussian Naive Bayes Classifier and SVM to classify the types based on the distribution of RGB pixels. However, the accuracy of those two methods was not acceptable.",
      "Finally, we used a CNN as the method to improve accuracy. To improve the generalization of the model, we implemented transforms to preprocess the images. We used AlexNet to construct the CNN model. The final accuracy testing on the test data was 78%.",
    ],
    link: "https://github.com/Shaddock-L/comp9417",
  },
  {
    id: 5,
    name: "COMP9321",
    type: "individual project",
    time: "Mar 2022 - Apr 2022",
    summary: "RESTtful API development.",
    achievements: [
      "Develop a Flask-Restx data service that allows a client to read and store information about an actor or actress, and allow the consumers to access the data through a REST API.",
      "The data of this project are from TV Maze API, which provides a detailed list of TV shows, actors, and actresses. This project will send request to this URL and use the response to modify the data base.",
      "This API implemented the POST, DELETE, PATCH, and GET methods, utilizing sqlite3 to create, read, update, and delete functions.",
    ],
    link: "https://github.com/Shaddock-L/ActorApi",
  },
];
